"""Error analysis for the FD001 RUL baseline.

Reads ``data/processed/test_predictions.csv`` (produced by
``train_baseline.py``) and writes ``reports/error_analysis.md``: the five
highest-error test units with a short, honest observation for each, plus a
summary of where the baseline is systematically weak.

Run:
    .venv/bin/python src/models/error_analysis.py
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.load_cmapss import RUL_CAP  # noqa: E402

PRED_PATH = ROOT / "data" / "processed" / "test_predictions.csv"
OUT_PATH = ROOT / "reports" / "error_analysis.md"

# A test unit with few observed cycles has seen little degradation.
SHORT_HISTORY_CYCLES = 50


def _observation(row: pd.Series) -> str:
    """One-line, evidence-based note for a single high-error unit."""
    true_rul = row["true_rul"]
    pred = row["pred_rul"]
    last_cycle = int(row["last_cycle"])
    signed = pred - true_rul
    direction = "over-predicts" if signed > 0 else "under-predicts"
    parts: list[str] = []

    if true_rul > RUL_CAP:
        parts.append(
            f"true RUL {true_rul} exceeds the {RUL_CAP}-cycle training cap, so the "
            f"capped model structurally cannot reach it — the under-prediction here "
            f"is expected, not a modelling failure"
        )
    if last_cycle < SHORT_HISTORY_CYCLES:
        parts.append(
            f"only {last_cycle} cycles of history observed, so the degradation signal "
            f"is still faint and the estimate is dominated by the healthy-baseline prior"
        )
    if signed > 0 and true_rul <= RUL_CAP:
        parts.append(
            "model reads the unit as healthier than it is (optimistic error) — the "
            "risky direction for maintenance, worth flagging"
        )
    if not parts:
        parts.append("large residual with no single obvious structural cause")

    return (
        f"{direction} by {abs(signed):.1f} cycles (pred {pred:.1f} vs true {true_rul}); "
        + "; ".join(parts)
        + "."
    )


def run() -> pd.DataFrame:
    df = pd.read_csv(PRED_PATH)
    df["error_signed"] = df["pred_rul"] - df["true_rul"]
    df["abs_error"] = df["error_signed"].abs()
    # Error against the capped truth, i.e. removing the structural cap penalty.
    true_capped = df["true_rul"].clip(upper=RUL_CAP)
    df["abs_error_capped"] = (df["pred_rul"] - true_capped).abs()

    worst = df.sort_values("abs_error", ascending=False).head(5).reset_index(drop=True)

    # Aggregate context for the honest-weakness section.
    n = len(df)
    n_over = int((df["error_signed"] > 0).sum())
    mean_signed = df["error_signed"].mean()
    over_cap = df[df["true_rul"] > RUL_CAP]
    short_hist = df[df["last_cycle"] < SHORT_HISTORY_CYCLES]
    corr_hist = np.corrcoef(df["last_cycle"], df["abs_error"])[0, 1]
    worst_in_cap_tail = int((worst["true_rul"] > RUL_CAP).sum())
    worst_optimistic = int((worst["error_signed"] > 0).sum())

    lines: list[str] = []
    lines.append("# FD001 RUL Baseline — Error Analysis\n")
    lines.append(
        "Generated by `src/models/error_analysis.py` from "
        "`data/processed/test_predictions.csv`. Errors are signed as "
        "`pred - true` against the **uncapped** official RUL unless stated otherwise.\n"
    )

    lines.append("## Five highest-error test units\n")
    lines.append("| unit | last cycle | true RUL | pred RUL | abs err (uncapped) | abs err (capped) |")
    lines.append("|-----:|-----------:|---------:|---------:|-------------------:|-----------------:|")
    for _, r in worst.iterrows():
        lines.append(
            f"| {int(r['unit_id'])} | {int(r['last_cycle'])} | {int(r['true_rul'])} | "
            f"{r['pred_rul']:.1f} | {r['abs_error']:.1f} | {r['abs_error_capped']:.1f} |"
        )
    lines.append("")
    for _, r in worst.iterrows():
        lines.append(f"- **Unit {int(r['unit_id'])}** — {_observation(r)}")
    lines.append("")

    lines.append("## Where the baseline is weak (honest notes)\n")
    lines.append(
        f"- **Cap-dominated tail (systematic under-prediction).** {len(over_cap)} of {n} test "
        f"units have true RUL above the {RUL_CAP}-cycle cap. The model is trained to saturate "
        f"at {RUL_CAP}, so on these units its error is bounded below by `true - {RUL_CAP}` and "
        f"cannot be removed without changing the target definition. This is a floor on error, "
        f"not the source of the largest residuals: {worst_in_cap_tail} of the top-5 units above "
        f"are in this tail."
    )
    lines.append(
        f"- **Optimistic over-prediction is the actual worst case.** {worst_optimistic} of the "
        f"top-5 residuals are over-predictions on mid-life units (true RUL below the cap) — the "
        f"model calls a moderately worn engine nearly healthy. Fleet-wide, mean signed error is "
        f"{mean_signed:+.1f} cycles with {n_over}/{n} units over-predicted. Over-prediction is "
        f"the operationally dangerous direction, so a deployment would pair this model with a "
        f"conservative risk-band threshold and human review, never the raw point estimate."
    )
    lines.append(
        f"- **Short-history units are hard.** {len(short_hist)} units end before cycle "
        f"{SHORT_HISTORY_CYCLES}. With little observed degradation the rolling features are "
        f"near their healthy baseline, so predictions collapse toward the cap "
        f"(correlation of |error| with observed history length = {corr_hist:+.2f})."
    )
    lines.append(
        "- **No uncertainty estimate.** A single RandomForest point prediction carries no "
        "calibrated confidence interval. Per-tree spread could give a rough uncertainty "
        "band; that is a clear next step and matters for the human-in-the-loop story."
    )
    lines.append(
        "- **Single fault mode, single condition.** FD001 has one operating condition and "
        "one fault mode (HPC degradation). These numbers will not transfer to FD002/FD004 "
        "(six conditions) without condition-aware normalisation."
    )
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"[write] {OUT_PATH}")
    print(worst[["unit_id", "last_cycle", "true_rul", "pred_rul", "abs_error"]].to_string(index=False))
    return worst


if __name__ == "__main__":
    run()
